on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    services:
      db:
        image: postgres:14
        ports: ['5432:5432']
        options: >-
        - health-cmd pg_isready
        - health-interval 10s
        - health-timeout 5s
        - health-retries 5

    uses: mtrudel/elixir-ci-actions/.github/workflows/test.yml@main
  lint:
    uses: mtrudel/elixir-ci-actions/.github/workflows/lint.yml@main