on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
    inputs:
      elixirs:
        type: string
        default: "[\"1.13.x\", \"1.14.x\", \"1.15.x\"]"
      erlangs:
        type: string
        default: "[\"24.x\", \"25.x\", \"26.x\"]"
      apt-packages:
        type: string
        default: ""

env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        elixir: ${{ fromJSON(inputs.elixirs) }}
        otp: ${{ fromJSON(inputs.erlangs) }}
        exclude:
          - elixir: 1.13.x
            otp: 26.x
    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          services:
            db:
              image: postgres
              env:
                POSTGRES_PASSWORD: postgres
              ports: ['5432:5432']
              options: >-
                --health-cmd pg_isready
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
    steps:
    - name: Install apt packages
      if: inputs.apt-packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ inputs.apt-packages }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}
    # This will disable warnings during dependency compilation, but since we
    # use --warnings-as-errors below for our own code, we'll see any warnings
    # generated by our own code
    - name: Disable compile warnings
      run: echo "::remove-matcher owner=elixir-mixCompileWarning::"
    - name: Retrieve mix dependencies cache
      uses: actions/cache@v4
      id: mix-cache
      with:
        path: |
          deps
          _build
        key: test-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: test-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-
    - name: Install mix dependencies
      if: steps.mix-cache.outputs.cache-hit != 'true'
      run: |
        mix deps.get
        mix deps.compile
    - name: Compile code
      run: mix compile --warnings-as-errors
    - name: Run tests
      run: mix test

  lint:
    uses: mtrudel/elixir-ci-actions/.github/workflows/lint.yml@main